repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--unsafe]
      - id: no-commit-to-branch
        args: [--branch, main]

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert]

  - repo: https://github.com/golangci/golangci-lint
    rev: v2.10.1
    hooks:
      - id: golangci-lint
        name: Lint
        args:
          - '--config=.golangci.yaml'
          - '--new'
          - '--verbose'
        exclude: |
          (?x)^(
                api/.*|
                build/.*|
                deployments/.*|
                docs/.*|
                mocks/.*|
                scripts/.*
            )$
        types:
          - go
        stages: [ pre-commit ]

  - repo: local
    hooks:
      - id: gitleaks
        name: gitleaks (staged diff scan)
        entry: gitleaks git . --staged --redact
        language: system
        pass_filenames: false
